### ISSUE TITLE
doctest doesn't return a non-zero result code when there's a failing test

### ISSUE THREAD

**Issue by heckj** [SwiftDocOrg/DocTest#10]
I got doctest up and kicking locally, and I'm starting to use it for verifying my README in my project. I'm working to get it included in CI for that project as well, as I'd like to see a CI explosion if the swift-doctest fails after I get it set up. Unfortunately, while it runs - it doesn't report a non-zero error code - so the failure isn't "seen" by the CI system.

I spotted where I think this might likely be added, but wasn't entirely sure enough when using Result objects to know how to roll up the details. My sense is "evaluate all the tests that have been consolidated" around [line 83 of main.swift](https://github.com/SwiftDocOrg/DocTest/blob/master/Sources/swift-doctest/main.swift#L83), but I didn't know if I could do something nice like `consolidatedReport.reports.map()` and somehow functionally filter to know if we should `system.exit(1)`.

Happy to stab in a PR, but it may be a bit before I add something while I work out this whole thing with `Results<>`. If it's blindingly obvious, please let me know ;-)

**Comment by mattt** [comment]
Fixed by #11. Thanks again, @heckj!
