### ISSUE TITLE
Provide a library product/target?

### ISSUE THREAD

**Issue by regexident** [SwiftDocOrg/DocTest#14]
Hi @mattt,

first of all: thank you so, so much for DocTest and all the other packages you published, which DocTest builds upon! 🙏🏻

I would really love to be able to use DocTest as a library dependency for a small project I'm working on.
Being able to directly call an API that's equivalent to the CLI of DocTest (and not requiring DocTest to be pre-installed as a binary) would help tremendously here.

**Comment by mattt** [comment]
Thanks for the kind words, @regexident!

I think that's a totally reasonable thing for the library to provide. I just opened #15 to do just that. Please give that a quick review when you have a chance, and I'll merge and cut a new release.

**Comment by regexident** [comment]
That was _way_ too quick, @mattt! 😮
I'm nowhere near ready for integrating it. 😂
